module.exports = {
  // Run tests single-threaded to avoid native module conflicts
  //maxWorkers: 1,
  testEnvironment: 'node',

  projects: [
    // v0.7.0 - Stable test suite (everything before v0.8.0)
    {
      displayName: 'v0.7.0',
      preset: 'ts-jest',
      testEnvironment: 'node',
      roots: ['<rootDir>/tests'],
      testMatch: ['**/*.test.ts'],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        // Exclude all v0.8.0 tests
        'WorkspaceService.test.ts',
        'VariableExtractorService.test.ts',
        'variable-extraction.test.ts',
        'ImportService.test.ts',
        'ExportService.test.ts',
        // Exclude all v0.9.0 UI/UX tests
        'TabManagerService.test.ts',
        'KeyboardShortcutManager.test.ts',
        'CommandPaletteService.test.ts',
        'FavoritesService.test.ts',
        'LayoutService.test.ts',
        'GlobalSearchService.test.ts',
        'RecentItems.test.tsx',
        'CollapsibleSection.test.tsx',
        'BreadcrumbNavigation.test.tsx',
        'EnhancedTabBar.test.tsx',
        'SplitViewManager.test.tsx',
        'AccessibilityControls.test.tsx',
        'ThemeCustomizer.test.tsx',
        'useResponsive.test.tsx',
        'KeyboardShortcuts.integration.test.tsx',
        'TabManagement.integration.test.tsx',
        'SearchAndNavigation.integration.test.tsx',
        'ThemeToggle.integration.test.tsx',
        // Exclude old v0.9.0 API tests
        'ConsoleService.test.ts',
        'console-integration.test.ts',
        'RequestAnalyzerService.test.ts',
        'OpenAPIGeneratorService.test.ts',
        'AsyncAPIGeneratorService.test.ts',
        'GraphQLSchemaGeneratorService.test.ts',
        'apispec-integration.test.ts',
        'DocumentationGeneratorService.test.ts',
        'MarkdownExporterService.test.ts',
        'SDKGeneratorService.test.ts',
        'ChangelogGeneratorService.test.ts',
        'PublishingService.test.ts',
        'SettingsService.test.ts',
      ],
      setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
      testTimeout: 10000,
      bail: 10,
      moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
      },
      collectCoverageFrom: [
        'src/**/*.ts',
        '!src/**/*.d.ts',
        '!src/renderer/**/*',
        '!src/main/index.ts',
        // Exclude v0.8.0 services from coverage
        '!src/main/services/WorkspaceService.ts',
        '!src/main/services/VariableExtractorService.ts',
        '!src/main/services/ImportService.ts',
        '!src/main/services/ExportService.ts',
        // Exclude v0.9.0 UI/UX services from coverage
        '!src/main/services/TabManagerService.ts',
        '!src/main/services/KeyboardShortcutManager.ts',
        '!src/main/services/CommandPaletteService.ts',
        '!src/main/services/FavoritesService.ts',
        '!src/main/services/LayoutService.ts',
        // Exclude v0.9.0 API services from coverage
        '!src/main/services/ConsoleService.ts',
        '!src/main/services/RequestAnalyzerService.ts',
        '!src/main/services/OpenAPIGeneratorService.ts',
        '!src/main/services/AsyncAPIGeneratorService.ts',
        '!src/main/services/GraphQLSchemaGeneratorService.ts',
      ],
      coverageDirectory: 'coverage/v0.7.0',
      coverageReporters: ['text', 'lcov', 'html'],
    },
    // v0.8.0 - New features (isolated test suite)
    {
      displayName: 'v0.8.0',
      preset: 'ts-jest',
      testEnvironment: 'node',
      roots: ['<rootDir>/tests'],
      testMatch: [
        '**/WorkspaceService.test.ts',
        '**/VariableExtractorService.test.ts',
        '**/variable-extraction.test.ts',
        '**/ImportService.test.ts',
        '**/ExportService.test.ts',
      ],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
      ],
      // No setupFilesAfterEnv - isolated environment to prevent mock interference
      testTimeout: 10000,
      moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
      },
      collectCoverageFrom: [
        'src/main/services/WorkspaceService.ts',
        'src/main/services/VariableExtractorService.ts',
        'src/main/services/ImportService.ts',
        'src/main/services/ExportService.ts',
      ],
      coverageDirectory: 'coverage/v0.8.0',
      coverageReporters: ['text', 'lcov', 'html'],
    },
    // v0.9.0 - UI/UX Overhaul + Tab System Redesign (isolated test suite)
    {
      displayName: 'v0.9.0',
      preset: 'ts-jest',
      testEnvironment: 'jsdom',
      roots: ['<rootDir>/tests'],
      testMatch: [
        // v0.9.0 UI/UX Services
        '**/TabManagerService.test.ts',
        '**/KeyboardShortcutManager.test.ts',
        '**/CommandPaletteService.test.ts',
        '**/FavoritesService.test.ts',
        '**/LayoutService.test.ts',
        '**/GlobalSearchService.test.ts',
        // v0.9.0 UI/UX Components
        '**/RecentItems.test.tsx',
        '**/CollapsibleSection.test.tsx',
        '**/BreadcrumbNavigation.test.tsx',
        '**/EnhancedTabBar.test.tsx',
        '**/SplitViewManager.test.tsx',
        '**/AccessibilityControls.test.tsx',
        '**/ThemeCustomizer.test.tsx',
        // v0.9.0 Hooks
        '**/useResponsive.test.tsx',
        // v0.9.0 Integration Tests
        '**/KeyboardShortcuts.integration.test.tsx',
        '**/TabManagement.integration.test.tsx',
        '**/SearchAndNavigation.integration.test.tsx',
        '**/ThemeToggle.integration.test.tsx',
        // Old v0.9.0 API tests (kept for backwards compatibility)
        '**/ConsoleService.test.ts',
        '**/console-integration.test.ts',
        '**/RequestAnalyzerService.test.ts',
        '**/OpenAPIGeneratorService.test.ts',
        '**/AsyncAPIGeneratorService.test.ts',
        '**/GraphQLSchemaGeneratorService.test.ts',
        '**/apispec-integration.test.ts',
        '**/DocumentationGeneratorService.test.ts',
        '**/MarkdownExporterService.test.ts',
        '**/SDKGeneratorService.test.ts',
        '**/ChangelogGeneratorService.test.ts',
        '**/PublishingService.test.ts',
        '**/SettingsService.test.ts',
      ],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
      ],
      testTimeout: 10000,
      moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
      },
      collectCoverageFrom: [
        // v0.9.0 UI/UX Services
        'src/main/services/TabManagerService.ts',
        'src/main/services/KeyboardShortcutManager.ts',
        'src/main/services/CommandPaletteService.ts',
        'src/main/services/FavoritesService.ts',
        'src/main/services/LayoutService.ts',
        // v0.9.0 UI/UX Components
        'src/renderer/components/RecentItems.tsx',
        'src/renderer/components/CollapsibleSection.tsx',
        'src/renderer/components/BreadcrumbNavigation.tsx',
        'src/renderer/components/EnhancedTabBar.tsx',
        // Old v0.9.0 API Services
        'src/main/services/ConsoleService.ts',
        'src/main/services/RequestAnalyzerService.ts',
        'src/main/services/OpenAPIGeneratorService.ts',
        'src/main/services/AsyncAPIGeneratorService.ts',
        'src/main/services/GraphQLSchemaGeneratorService.ts',
        'src/main/services/DocumentationGeneratorService.ts',
        'src/main/services/MarkdownExporterService.ts',
        'src/main/services/SDKGeneratorService.ts',
        'src/main/services/ChangelogGeneratorService.ts',
        'src/main/services/PublishingService.ts',
        'src/main/services/SettingsService.ts',
      ],
      coverageDirectory: 'coverage/v0.9.0',
      coverageReporters: ['text', 'lcov', 'html'],
    },
  ],
  // Global coverage settings
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
};
