blank_issues_enabled: true # force the usage of a template
contact_links:
  - name: Feature Requests, support and consulting
    url: https://github.com/sponsors/petyosi
    about: If you have troubles integrating MDXEditor and you can sponsor the project in exchange of dedicated assistance, contact me over my the email in my profile.
